import {ProjectsPanel} from './projects-panel.jsx';
import {ExpensePanel} from './expense-panel.jsx';
import {UsersPanel, OrganizationPanel, SettingsPanel} from './admin-panels.jsx';
import {DealsPanel} from './deals-panel.jsx';
import {FinancePanel, seedFinance} from './finance-panel.jsx';
import {RevenuePanel, withLedger} from './revenue-panel.jsx';
import {AccountsPanel, AccessPanel, ActivitiesPanel} from './workflow-panels.jsx';
import React,{useState,useEffect,useRef} from 'react';
import {SquaresFour,Handshake,Receipt,Wallet,CalendarCheck,NotePencil,ChatsCircle,Flag,Lightbulb,Buildings,Users,ChartBar,Coins,ClockCounterClockwise,Gear,ShieldCheck,List,X,Plus,ArrowRight,ArrowLeft,DownloadSimple,Printer,CheckCircle,WarningCircle,FunnelSimple,MagnifyingGlass,CaretRight,ArrowCounterClockwise,Lock,SignIn} from '@phosphor-icons/react';
import Chart from 'chart.js/auto';
import '@fontsource/noto-sans-jp/400.css';
import '@fontsource/noto-sans-jp/500.css';
import '@fontsource/noto-sans-jp/700.css';
import '@fontsource/zen-kaku-gothic-new/700.css';
import {businesses as baseBusinesses,members as baseMembers,stages,seedDeals,seedRevenue,seedExpenses,rangeFor,screenCatalog} from './data.js';
const icons={dashboard:SquaresFour,deals:Handshake,revenue:Receipt,expenses:Wallet,closing:CalendarCheck,activities:NotePencil,support:ChatsCircle,projects:Flag,ideas:Lightbulb,accounts:Buildings,organization:Users,budgets:ChartBar,payroll:Coins,audit:ClockCounterClockwise,users:Users,access:ShieldCheck,settings:Gear,login:SignIn};
const money=n=>'¥'+Number(n).toLocaleString('ja-JP');
const fmt=s=>s?.replaceAll('-','/');
const roles=['経営者','総務担当','システム担当'];
const TODAY='2026-09-11';
const field=(name,label,type='text',options,extra={})=>({name,label,type,options,required:true,...extra});
const options=(items,empty)=>[...(empty?[empty]:[]),...items];
function Tag({children,tone='neutral'}){return <span className={'tag '+tone}>{children}</span>}
function Panel({title,subtitle,action,children,className=''}){return <section className={'panel '+className}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
function ChartView({confirmed,pending,labels,light}){
 const canvas=useRef(null);
 useEffect(()=>{const chart=new Chart(canvas.current,{type:'bar',data:{labels,datasets:[{label:'確定分',data:confirmed,backgroundColor:'#5977B0',borderRadius:4,maxBarThickness:54},{label:'未確定分',data:pending,backgroundColor:'#BCC9E4',borderRadius:4,maxBarThickness:54}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{x:{stacked:true,grid:{display:false},ticks:{color:light?'#49516A':'#AEB4D4'}},y:{stacked:true,beginAtZero:true,grid:{color:'#2B3153'},border:{display:false},ticks:{color:light?'#49516A':'#AEB4D4',callback:n=>n/10000+'万'}}}}});return()=>chart.destroy()},[confirmed.join(','),pending.join(','),labels.join(','),light]);
 return <div className="chart"><canvas ref={canvas} role="img" aria-label={`着地見込み。${labels.map((x,i)=>`${x}: 確定分${money(confirmed[i])}、未確定分${money(pending[i])}`).join('。')}`}/></div>
}
function Dialog({spec,onClose,scenario,changed}){
 const ref=useRef(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[conflictResolved,setConflictResolved]=useState(false),[draft,setDraft]=useState({});
 useEffect(()=>{ref.current.showModal()},[]);
 const formValues=form=>{const data=new FormData(form);const values=Object.fromEntries(data);for(const f of spec.fields||[])if(f.type==='multiselect')values[f.name]=data.getAll(f.name);return values};
 const submit=e=>{e.preventDefault();const f=formValues(e.currentTarget);setDraft(f);const invalid=spec.validate?.(f);if(invalid){setError(invalid);setConfirmed(false);return}if(spec.confirm&&!confirmed){setConfirmed(true);return}if(scenario==='競合'&&!conflictResolved){setError('ほかの利用者が更新しました。現在値と自分の変更を比較し、再確認してください。');return}if(scenario==='通信エラー'){setError('保存できませんでした。入力内容は保持しています。時間をおいて再試行してください。');return}const result=spec.save?.(f);if(typeof result==='string'){setError(result);setConfirmed(false);return}changed(spec.success||'保存しました。',f,spec);onClose()};
 return <dialog ref={ref} onCancel={onClose} aria-labelledby="dialog-title"><form onSubmit={submit} onChange={e=>{setConfirmed(false);if(scenario!=='競合')setError('');setDraft(formValues(e.currentTarget))}}><header><div><p className="eyebrow">{spec.eyebrow||'内容の確認'}</p><h2 id="dialog-title">{spec.title}</h2></div><button type="button" className="icon-btn" onClick={onClose} aria-label="閉じる"><X size={21}/></button></header>
 <div className="dialog-body">{spec.text&&<p className="dialog-intro">{spec.text}</p>}{spec.content}
 <div className="form-grid">{spec.fields?.map(f=><label key={f.name} className={f.type==='textarea'?'wide':''}>{f.label}{f.required&&<span className="required">必須</span>}{['select','multiselect'].includes(f.type)?<select multiple={f.type==='multiselect'} name={f.name} defaultValue={f.value||''} required={f.required}>{f.type==='select'&&<option value="">選択してください</option>}{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value||''} required={f.required} rows={3}/>:<input name={f.name} type={f.type} defaultValue={f.value??''} required={f.required} min={f.type==='number'?(f.min??0):undefined} max={f.max} step={f.type==='number'?1:undefined} readOnly={f.readOnly}/>}</label>)}</div>
 {spec.hint&&<div className="form-hint">{spec.hint(draft)}</div>}
 {spec.confirm&&confirmed&&<div className="notice"><CheckCircle size={20}/><div>次の内容で登録します。<dl className="confirmation-values">{spec.fields?.map(f=><React.Fragment key={f.name}><dt>{f.label}</dt><dd>{Array.isArray(draft[f.name])?draft[f.name].join('、')||'なし':draft[f.name]||'未設定'}</dd></React.Fragment>)}</dl>よろしければ「確定する」を押してください。</div></div>}
 {error&&<div className="notice danger" role="alert"><WarningCircle size={22}/><div>{error}{scenario==='競合'&&Object.keys(draft).length>0&&<dl className="conflict-values">{spec.fields?.map(f=><React.Fragment key={f.name}><dt>{f.label}</dt><dd>現在値：{f.value||'未設定'}<br/>自分の変更：{Array.isArray(draft[f.name])?draft[f.name].join('、')||'なし':draft[f.name]||'未設定'}</dd></React.Fragment>)}</dl>}{scenario==='競合'&&<p><button type="button" onClick={()=>{for(const f of spec.fields||[]){const element=ref.current.querySelector(`[name="${f.name}"]`);if(element){if(f.type==='multiselect'){for(const option of element.options)option.selected=(f.value||[]).includes(option.value)}else element.value=f.value||''}}setDraft(formValues(ref.current.querySelector('form')));setError('');setConflictResolved(true);setConfirmed(false)}}>現在値を再読み込み</button><button type="button" onClick={()=>{setError('');setConflictResolved(true);setConfirmed(false)}}>自分の変更を再適用</button></p>}</div></div>}</div>
 <footer><button type="button" onClick={onClose}>キャンセル</button><button type="submit" className={spec.danger?'danger-btn':'primary'}>{spec.confirm?(confirmed?'確定する':'内容を確認'):spec.button||'保存する'}</button></footer></form></dialog>
}
export function App(){
 const [organization,setOrganization]=useState({businesses:baseBusinesses.map((name,i)=>({id:'B-'+i,name,start:'2025-10-01',active:true})),members:baseMembers.map((name,i)=>({id:'M-'+i,name,start:'2025-10-01',primary:baseBusinesses[i],additional:i===0?['企業研修']:[],active:true}))});
 const businesses=organization.businesses.filter(x=>x.active).map(x=>x.name),members=organization.members.filter(x=>x.active).map(x=>x.name);
 const [users,setUsers]=useState([{id:'U-1',email:'executive@example.test',role:'経営者',active:true},{id:'U-2',email:'office@example.test',role:'総務担当',active:true},{id:'U-3',email:'system@example.test',role:'システム担当',active:true}]);
 const [settings,setSettings]=useState({integration:false,startedBy:'経営者（サンプル）',startedAt:'2026/09/01 09:00'});
 const [role,setRole]=useState('経営者'),[route,setRoute]=useState('dashboard'),[menu,setMenu]=useState(false),[scenario,setScenario]=useState('通常'),[toast,setToast]=useState(''),[dialog,setDialog]=useState(null),[printPreview,setPrintPreview]=useState(false);
 const [focusDeal,setFocusDeal]=useState(null);
 const [deals,setDeals]=useState(seedDeals),[revenue,setRevenue]=useState(seedRevenue.map(withLedger)),[expenses,setExpenses]=useState(seedExpenses),[closing,setClosing]=useState('未締め'),[closeReady,setCloseReady]=useState(false),[closeHistory,setCloseHistory]=useState([]);
 const [period,setPeriod]=useState('1か月'),[month,setMonth]=useState('2026-09'),[part,setPart]=useState(0),[business,setBusiness]=useState('すべての事業'),[member,setMember]=useState('すべての担当'),[stage,setStage]=useState('すべての段階'),[search,setSearch]=useState(''),[expenseTab,setExpenseTab]=useState('すべて');
 const [access,setAccess]=useState('未申請'),[accessRequest,setAccessRequest]=useState({reason:'未申請',requestedAt:'—',applicant:'システム担当（サンプル）'}),[productionStarted,setProductionStarted]=useState(true),[accessExpired,setAccessExpired]=useState(false),[comments,setComments]=useState([{id:1,business:'FP事業',member:'担当A',text:'次回の相談では、継続支援の内容を具体化。必要なら提案前に一緒に確認したい。',at:'2026/09/10 16:30'}]);
 const [activities,setActivities]=useState([{id:'ACT-001',name:'提案内容の確認',business:'FP事業',member:'担当A',date:'2026-09-08',next:'2026-09-10',status:'未着手'}]);
 const [nextActions,setNextActions]=useState([{id:'NA-001',activityId:'ACT-001',text:'提案資料を送付する',owner:'担当A',business:'FP事業',timing:'期限',start:'',end:'2026-09-10',status:'未着手'}]);
 const [accounts,setAccounts]=useState([{id:'A-001',name:'サンプル商事',type:'法人'},{id:'A-002',name:'サンプル企画',type:'法人'},{id:'A-003',name:'サンプル工業',type:'法人'},{id:'A-004',name:'サンプル不動産',type:'法人'}]);
 const [ideas,setIdeas]=useState([{text:'新規相談の前に、事前アンケートを共通化する。',business:'FP事業',status:'検討中'}]);
 const [finance,setFinance]=useState(seedFinance);
 const [projects,setProjects]=useState([{name:'採用サイトの見直し',due:'2026-09-30',owner:'担当C',status:'進行中',budget:300000,outcome:'募集要件のたたき台を作成',problem:'写真素材の準備'}]);
 const [audit,setAudit]=useState([{at:'2026/09/10 16:30',who:'総務（サンプル）',what:'売上を計上',subject:'管理職研修 秋季プログラム',reason:'通常入力'}]);
 const executive=role==='経営者',system=role==='システム担当',sensitive=executive||(system&&(!productionStarted||(access==='許可中'&&!accessExpired)));
 const available=id=>!(['support','budgets','payroll'].includes(id)&&!sensitive)&&!(id==='users'&&!system)&&!(id==='settings'&&!system&&!executive)&&!(id==='access'&&role==='総務担当')&&!(id==='audit'&&role==='総務担当');
 const nav=screenCatalog.filter(([id])=>id!=='login'&&available(id));
 const drawer=useRef(null),menuOpener=useRef(null);
 useEffect(()=>{if(!menu)return;const prev=document.activeElement;const node=drawer.current;node.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();setMenu(false)}if(e.key==='Tab'){const list=[...node.querySelectorAll('button:not(:disabled),a[href],select,input')];const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};node.addEventListener('keydown',key);return()=>{node.removeEventListener('keydown',key);if(prev?.isConnected)prev.focus()}},[menu]);
 const range=rangeFor(period,month,part);const inRange=d=>d>=range.start&&d<=range.end;
 const match=row=>!row.cancelled&&(business==='すべての事業'||row.business===business)&&(member==='すべての担当'||row.member===member)&&(stage==='すべての段階'||(deals.find(d=>d.id===row.deal)?.stage||row.stage||'成約')===stage);
 const ledgerRevenue=revenue.map(withLedger);
 const salesEvents=ledgerRevenue.filter(match).flatMap(r=>r.entries.filter(e=>e.kind==='売上').map(e=>({...r,amount:e.amount,date:e.date})));
 const scoped=[...salesEvents.filter(r=>inRange(r.date)),...ledgerRevenue.filter(r=>match(r)&&!r.booked&&deals.find(d=>d.id===r.deal)?.stage==='成約'&&!deals.find(d=>d.id===r.deal)?.cancelled&&inRange(r.date))],actual=salesEvents.filter(r=>inRange(r.date)).reduce((n,r)=>n+r.amount,0),confirmed=scoped.reduce((n,r)=>n+r.amount,0),potential=deals.filter(d=>match(d)&&inRange(d.revenueDate)&&!d.cancelled&&!['成約','失注'].includes(d.stage)).reduce((n,d)=>n+d.amount,0);
 const previousActual=salesEvents.filter(r=>r.date>=range.prevStart&&r.date<=range.prevEnd).reduce((n,r)=>n+r.amount,0);
 const balanceAt=kind=>ledgerRevenue.filter(match).flatMap(r=>r.entries.filter(e=>e.kind===kind&&e.date<=range.end)).reduce((n,e)=>n+e.amount,0);
 const chartBusinesses=business==='すべての事業'?[...new Set([...scoped.map(r=>r.business),...deals.filter(d=>match(d)&&inRange(d.revenueDate)&&!d.cancelled&&!['成約','失注'].includes(d.stage)).map(d=>d.business)])]:[business];
 const periodFinance=finance.filter(x=>x.month>=range.start.slice(0,7)&&x.month<=range.end.slice(0,7));
 const sumFinance=(kind)=>periodFinance.reduce((n,x)=>n+(typeof x[kind]==='number'?x[kind]:business==='すべての事業'?Object.values(x[kind]).reduce((a,b)=>a+b,0):x[kind][business]||0),0);
 const payrollValue=sumFinance('payroll'),salesBudget=sumFinance('sales'),expenseBudget=sumFinance('costs')+(business==='すべての事業'?sumFinance('common'):0);
 const monthExpenses=expenses.filter(e=>inRange(e.date)),scopedExpenses=monthExpenses.filter(e=>business==='すべての事業'||e.business===business),cost=scopedExpenses.reduce((n,e)=>n+e.amount,0),restrictedFilter=member!=='すべての担当'||stage!=='すべての段階';
 const go=id=>{setPrintPreview(false);setRoute(id);setMenu(false);setSearch('');setScenario('通常')};
 useEffect(()=>{window.scrollTo(0,0)},[route]);
 const notify=(text,values={},spec={})=>{setToast(text);setAudit(a=>[{at:new Date().toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}),who:role+'（サンプル）',what:text,subject:spec.title||screenCatalog.find(x=>x[0]===route)?.[1],reason:values.reason||'通常操作',restricted:['support','budgets','payroll'].includes(route)||(spec.fields||[]).some(f=>f.name==='budget'),values:JSON.stringify(values)},...a])};
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(!available(route))setRoute(system?'settings':'dashboard')},[role,access,accessExpired,productionStarted]);
 useEffect(()=>{if(access!=='許可中'||!accessRequest.until)return;const remaining=accessRequest.until-Date.now();if(remaining<=0){setAccessExpired(true);return}const t=setTimeout(()=>setAccessExpired(true),remaining);return()=>clearTimeout(t)},[access,accessRequest.until]);
 const roleChange=r=>{setPrintPreview(false);setRole(r);setDialog(null);setScenario('通常');setRoute(r==='システム担当'?'settings':'dashboard')};
 const begin=spec=>setDialog(spec);
 useEffect(()=>{setCloseReady(false)},[expenses,revenue,finance]);
 const saveGuard=(date='2026-09-01')=>closing==='締め済み'&&date.startsWith('2026-09')?'この月は締め済みです。経営者に締め解除を依頼してください。':undefined;

 const table=(headers,rows)=><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j} data-label={headers[j]}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty"><MagnifyingGlass size={28}/><h3>該当するデータがありません</h3><p>検索語や絞り込み条件を変更してください。</p></div>}</div>;
 const searchbar=(label='名称で検索')=><label className="search"><MagnifyingGlass size={19}/><span className="sr-only">{label}</span><input value={search} placeholder={label} onChange={e=>setSearch(e.target.value)}/></label>;
 const filters=<div className="filters"><label><FunnelSimple size={17}/><span className="sr-only">事業</span><select aria-label="事業で絞り込み" value={business} onChange={e=>setBusiness(e.target.value)}>{options(businesses,'すべての事業').map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">担当者</span><select aria-label="担当者で絞り込み" value={member} onChange={e=>setMember(e.target.value)}>{options(members,'すべての担当').map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">案件段階</span><select aria-label="案件段階で絞り込み" value={stage} onChange={e=>setStage(e.target.value)}>{options(stages,'すべての段階').map(x=><option key={x}>{x}</option>)}</select></label><button className="text-btn" onClick={()=>{setBusiness('すべての事業');setMember('すべての担当');setStage('すべての段階')}}>条件をクリア</button></div>;
 const exportCsv=()=>{
  const rows=[['分析期間',range.start,range.end],['比較期間',range.prevStart,range.prevEnd],['事業',business],['担当',member],['段階',stage],['売上計上額',actual],['売上着地見込み',confirmed+potential],['確定分',confirmed],['未確定分',potential],['未請求額',balanceAt('売上')-balanceAt('請求')],['未入金額',balanceAt('請求')-balanceAt('入金')]];
  if(!restrictedFilter)rows.push(['経費総額',cost],['経費見直し候補',scopedExpenses.filter(e=>e.review).reduce((n,e)=>n+e.amount,0)]);
  if(sensitive&&!restrictedFilter){rows.push([period==='10日毎'?'売上予算（月次参考）':'売上予算',salesBudget],[period==='10日毎'?'経費予算（月次参考）':'経費予算',expenseBudget],[period==='10日毎'?'全社人件費（月次参考）':'全社人件費',payrollValue]);if(period!=='10日毎'||business!=='すべての事業')rows.push([business==='すべての事業'?'全社利益':'事業利益',actual-cost-(business==='すべての事業'?payrollValue:0)]);}
  const q=v=>'"'+(typeof v==='string'&&/^[=+@-]/.test(v)?"'"+v:String(v)).replaceAll('"','""')+'"';
  const csv='\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n');
  begin({title:'CSVの内容を確認',text:'現在の期間・フィルター・閲覧権限を反映しています。内容を確認して保存できます。',content:<div><label className="csv-preview">CSVデータ<textarea aria-label="CSVデータ" readOnly value={csv} rows={14}/></label><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(csv);notify('CSVの内容をコピーしました。')}catch{notify('CSVデータ欄を選択してコピーしてください。')}}}>CSVをコピー</button><p className="small">ファイル保存に対応していないブラウザーでは、内容をコピーして利用できます。</p></div>,button:'ファイルを保存',save:()=>{const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download='ATT_画面案_架空集計.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},success:'CSVの保存を要求しました。ブラウザーのダウンロードをご確認ください。'});

 };
 const downloadAudit=()=>{const rows=audit.filter(a=>sensitive||!a.restricted);const csv=['日時,実行者,操作,対象,理由',...rows.map(a=>[a.at,a.who,a.what,a.subject,a.reason].map(x=>'\"'+String(x??'').replaceAll('\"','\"\"')+'\"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='ATT_画面案_監査履歴.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const headerActions=route==='dashboard'?<><button onClick={exportCsv}><DownloadSimple size={17}/>CSV</button><button onClick={()=>setPrintPreview(true)}><Printer size={17}/>印刷</button></>:null;
 function dashboard(){return <>
 <div className="period-bar"><div className="segments" aria-label="分析期間">{['10日毎','1か月','3か月','6か月','1年'].map(p=><button key={p} aria-pressed={period===p} className={p===period?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div><label className="month"><span className="sr-only">対象月</span><input type="month" value={month} min="2025-10" max="2026-09" onChange={e=>e.target.value&&setMonth(e.target.value)}/></label>{period==='10日毎'&&<select aria-label="管理区分" value={part} onChange={e=>setPart(Number(e.target.value))}>{['上旬（1〜10日）','中旬（11〜20日）','下旬（21日〜月末）'].map((p,i)=><option key={p} value={i}>{p}</option>)}</select>}</div>
 {printPreview&&<p className="print-conditions">{business} / {member} / {stage}</p>}
 <p className="range">{fmt(range.start)} — {fmt(range.end)} <span>比較：{fmt(range.prevStart)} — {fmt(range.prevEnd)}</span></p>{filters}
 {restrictedFilter&&<p className="notice">担当者・案件段階での絞り込み中です。経費・予算・利益は集計対象から外れます。</p>}
 <div className="metrics"><Metric label="売上計上額" value={money(actual)} sub="計上実績日の合計"/><Metric label="売上着地見込み" value={money(confirmed+potential)} sub={`確定分 ${money(confirmed)} / 未確定分 ${money(potential)}`}/>{!restrictedFilter&&<><Metric label="経費総額" value={money(cost)} sub={`利用日の実績 · 人件費を除く${business==='すべての事業'?' · 未分類を含む':''}`}/>{sensitive&&<Metric label={business==='すべての事業'?'全社利益':'事業利益'} value={period==='10日毎'&&business==='すべての事業'?'—':money(actual-cost-(business==='すべての事業'?payrollValue:0))} sub={period==='10日毎'&&business==='すべての事業'?'10日毎では全社利益を計算しません':business==='すべての事業'?'経費・全社人件費を控除':'全社共通費・人件費の配賦前'}/>}</>}</div>
 <div className="dashboard-grid"><Panel title="売上の着地見込み" subtitle="選択期間の事業別内訳" action={<Tag>税込</Tag>}><ChartView light={printPreview} confirmed={chartBusinesses.map(b=>scoped.filter(r=>r.business===b).reduce((n,r)=>n+r.amount,0))} pending={chartBusinesses.map(b=>deals.filter(d=>d.business===b&&match(d)&&inRange(d.revenueDate)&&!d.cancelled&&!['成約','失注'].includes(d.stage)).reduce((n,d)=>n+d.amount,0))} labels={chartBusinesses}/><div className="legend"><span><i className="solid"/>確定分 {money(confirmed)}</span><span><i className="pale"/>未確定分 {money(potential)}</span></div><p className="small">確定分＝計上済み＋成約済みの未計上予定。未確定分は全件成約した場合の金額です。</p></Panel>
 <Panel title="確認すること" subtitle="未完了の入力と次の行動"><button className="action-row" onClick={()=>{setExpenseTab('対象未分類');go('expenses')}}><Wallet size={22}/><span><strong>経費の対象事業</strong><small>未分類 {expenses.filter(e=>!e.business).length}件</small></span><CaretRight/></button><button className="action-row" onClick={()=>go('revenue')}><Receipt size={22}/><span><strong>請求・入金の確認</strong><small>入金待ち {money(revenue.reduce((n,r)=>n+r.invoiced-r.paid,0))}</small></span><CaretRight/></button><button className="action-row" onClick={()=>go('activities')}><CalendarCheck size={22}/><span><strong>次の行動を確認</strong><small>期限超過 {nextActions.filter(a=>a.status==='未着手'&&a.end&&a.end<TODAY).length}件</small></span><CaretRight/></button><div className="closing-mini"><span>9月の月次締め</span><Tag>{closing}</Tag><p>目標：2026/10/10</p><button className="text-btn" onClick={()=>go('closing')}>締め状況を見る <ArrowRight size={16}/></button></div></Panel></div>
 {sensitive&&!restrictedFilter&&<Panel title={period==='10日毎'?`${month} の月次参考`:'対象期間の予算と経費の内訳'} subtitle={period==='10日毎'?'月次予算・人件費は日割りせず、実績と分けて表示':'架空の月次予算・人件費'}><div className="summary-strip"><div>売上予算<strong>{money(salesBudget)}</strong></div><div>経費予算<strong>{money(expenseBudget)}</strong></div><div>全社人件費<strong>{money(payrollValue)}</strong></div>{period!=='10日毎'&&<div>売上の予算差<strong>{money(actual-salesBudget)}</strong></div>}<div>全社共通費<strong>{money(monthExpenses.filter(e=>e.business==='全社共通').reduce((n,e)=>n+e.amount,0))}</strong></div></div></Panel>}
 <Panel title="期間の比較と残高" subtitle="未請求・未入金は表示期間末までの累積残高です。">{table(['指標','選択期間','比較期間・差額'],[
 ['売上計上額',money(actual),salesEvents.some(r=>r.date>=range.prevStart&&r.date<=range.prevEnd)?<>{money(previousActual)}<small>差額 {money(actual-previousActual)}</small></>:'比較期間の実績データなし'],
 ['全件成約時見込み（未確定分）',money(potential),'成約確率による重み付けなし'],
 ['未請求額',money(balanceAt('売上')-balanceAt('請求')),'期間末までの売上実績 − 請求実績'],['未入金額',money(balanceAt('請求')-balanceAt('入金')),'期間末までの請求実績 − 入金実績'],
 ...(!restrictedFilter?[['見直し候補の経費',money(scopedExpenses.filter(e=>e.review).reduce((n,e)=>n+e.amount,0)),<button onClick={()=>{setExpenseTab('見直し候補');go('expenses')}}>明細を見る</button>]]:[])
 ])}</Panel>
 <Panel title="期間内の案件変更" subtitle="画面案で行った変更を表示。過去時点の復元は本実装で検証します。">{table(['案件','変更前 → 変更後','理由'],deals.filter(match).flatMap(d=>(d.history||[]).map(h=>[d.name,`${h.before} → ${h.after}`,h.reason])))}</Panel>
 <Panel title="案件の状況" subtitle="2026年9月の案件サンプル" action={<button className="text-btn" onClick={()=>go('deals')}>案件一覧 <ArrowRight size={16}/></button>}>{table(['案件','事業・担当','段階','金額'],deals.filter(match).map(d=>[<button className="text-btn" onClick={()=>dealDetail(d)}>{d.name}</button>,<>{d.business}<small>{d.member}</small></>,<Tag>{d.stage}</Tag>,money(d.amount)]))}</Panel>
 {sensitive&&<Panel title="支援記録" subtitle="経営者だけに共有するコメント" action={executive&&<button onClick={addComment}><Plus size={17}/>コメント</button>}>{comments.slice(0,2).map(c=><article className="comment" key={c.id}><p>{c.text}</p><small>{c.business} · {c.member} · 経営者（サンプル） · {c.at}</small></article>)}</Panel>}
 </>}
 function Metric({label,value,sub}){return <section className="metric"><p>{label}</p><strong>{value}</strong><small>{sub}</small></section>}
 function addComment(source){source=source?.id?source:undefined;begin({title:'支援コメントを記録',text:source?`訂正対象：${source.text}`:'投稿後は上書きせず、訂正コメントを追記します。',fields:[field('business','対象事業','select',businesses,{required:false,value:source?.business}),field('member','対象メンバー','select',members,{required:false,value:source?.member}),field('deal','関連案件','select',deals.map(d=>d.name),{required:false}),field('activity','関連活動','select',activities.map(a=>a.name),{required:false}),field('text','コメント','textarea')],save:f=>{if(!f.business&&!f.member)return '対象事業または対象メンバーを一つ以上選んでください。';setComments(cs=>[{...f,correctionOf:source?.id,id:Date.now(),at:new Date().toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})},...cs])},success:'支援コメントを記録しました。'})}
 function dealDetail(d){setFocusDeal(d.id);go('deals')}
 function closingView(){const pending=expenses.filter(e=>!e.business).length+(scenario==='連携確認待ち'?1:0);const locked=closing==='締め済み';return <><div className="period-bar"><h2>2026年9月</h2><Tag tone={locked?'good':'warn'}>{closing}</Tag><span className="small">締め目標日：2026/10/10</span></div><Panel title="締める前に確認" subtitle="直前の連携確認が完了してから締めを確定します。"><div className="check-row"><span>経費の対象事業</span>{pending?<button className="text-btn" onClick={()=>{setExpenseTab('対象未分類');go('expenses')}}>未回答 {pending}件を確認 <ArrowRight size={17}/></button>:<Tag tone="good">確認済み</Tag>}</div><div className="check-row"><span>連携確認待ち</span><Tag tone={scenario==='連携確認待ち'?'warn':'good'}>{scenario==='連携確認待ち'?'1件・解析結果の確認が必要':'0件'}</Tag></div><div className="check-row"><span>Slackとの直前照合</span>{scenario==='照合失敗'&&<span role="alert">接続に失敗。締めは実行できません。</span>}<Tag tone={closeReady?'good':'warn'}>{closeReady?'照合済み（画面案）':'未実施'}</Tag></div><div className="check-row"><span>売上・請求・入金</span><button className="text-btn" onClick={()=>go('revenue')}>明細を見る <ArrowRight size={17}/></button></div><div className="panel-footer">{!locked&&<button onClick={()=>{if(scenario==='照合失敗'||scenario==='通信エラー'){setCloseReady(false);notify('照合に失敗しました。再試行してください。');return}setCloseReady(true);notify('画面案の照合を完了しました。')}}>照合を実行</button>}{executive?locked?<button onClick={()=>begin({title:'9月の締めを解除',text:'解除後は明細を編集できます。訂正後は再度締めてください。',fields:[field('reason','解除理由','textarea')],confirm:true,save:f=>{setClosing('再締め待ち');setCloseReady(false);setCloseHistory(h=>[...h,{version:'解除',date:'2026/09/11',by:role,reason:f.reason}])},success:'締めを解除しました。'})}>理由を付けて解除</button>:<button disabled={pending>0||!closeReady} className="primary" onClick={()=>begin({title:'2026年9月を締める',text:'売上・経費・予算などの通常編集を停止します。訂正には理由付きの締め解除が必要です。',confirm:true,save:()=>{setClosing('締め済み');setCloseHistory(h=>[...h,{version:h.filter(x=>x.version!=='解除').length+1,date:'2026/09/11',by:'経営者（サンプル）'}])},success:'2026年9月を締めました。'})}>月次を締める</button>:<p className="small">総務担当は下書き・確認まで行えます。確定は経営者が行います。</p>}</div></Panel><Panel title="締めの履歴" subtitle="過去の締め版は保持します。"><p className="muted">{closeHistory.length?closeHistory.map((h,i)=><span key={i}>{h.version==='解除'?'締め解除':`第${h.version}版`} · {h.date} · {h.by}{h.reason&&` · 理由：${h.reason}`}<br/></span>):'この月の締めはまだ確定していません。'}</p></Panel></>}
 function secondary(){
 if(route==='support')return <Panel title="支援コメント" subtitle="経営者限定。訂正は新しいコメントで追記します。" action={executive&&<button className="primary" onClick={addComment}><Plus size={17}/>コメントを記録</button>}>{comments.map(c=><article className="comment" key={c.id}><Tag>{c.business||c.member}</Tag>{c.correctionOf&&<small>先のコメントへの訂正</small>}<p>{c.text}</p>{(c.deal||c.activity)&&<small>{[c.deal&&`関連案件：${c.deal}`,c.activity&&`関連活動：${c.activity}`].filter(Boolean).join(' · ')}</small>}<small>{c.member?`${c.member} · `:''}経営者（サンプル） · {c.at}</small>{executive&&<button className="text-btn" onClick={()=>addComment(c)}>訂正を追記</button>}</article>)}</Panel>;
 if(route==='activities')return <ActivitiesPanel activities={activities} setActivities={setActivities} actions={nextActions} setActions={setNextActions} members={members} businesses={businesses} deals={deals} begin={begin} role={role} today={TODAY}/>;
 if(route==='projects')return <ProjectsPanel projects={projects} setProjects={setProjects} executive={executive} sensitive={sensitive} members={members} begin={begin}/>;
 if(route==='ideas')return <Panel title="アイデア受信箱" subtitle="思いつきを、一つのメモで残す" action={<button className="primary" onClick={()=>begin({title:'アイデアを投稿',fields:[field('text','アイデアメモ','textarea'),field('business','関連事業','select',businesses,{required:false})],save:f=>setIdeas(xs=>[{...f,status:'未整理',at:new Date().toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}),author:role},...xs])})}><Plus size={17}/>アイデアを投稿</button>}>{ideas.map((v,i)=><article className="comment" key={i}><p>{v.text}</p><div className="toolbar"><small>{v.business} · Web入力 · {v.author||'経営者'} · {v.at||'2026/09/10 14:00'}</small><select aria-label={`アイデア${i+1}の状態`} value={v.status} onChange={e=>setIdeas(xs=>xs.map((x,j)=>i===j?{...x,status:e.target.value}:x))}>{!executive&&!['未整理','検討中'].includes(v.status)&&<option disabled>{v.status}</option>}{(executive?['未整理','検討中','採用','保留','却下']:['未整理','検討中']).map(s=><option key={s}>{s}</option>)}</select></div></article>)}</Panel>;
 if(route==='accounts')return <AccountsPanel accounts={accounts} setAccounts={setAccounts} setDeals={setDeals} begin={begin} role={role}/>;
 if(route==='budgets'||route==='payroll')return <FinancePanel finance={finance} setFinance={setFinance} month={month} setMonth={setMonth} businesses={businesses} route={route} begin={begin} saveGuard={saveGuard} executive={executive}/>;
 if(route==='audit')return <Panel title="変更・操作の履歴" subtitle="閲覧できる情報の範囲で履歴を確認" action={sensitive&&<button onClick={downloadAudit}>CSVを出力</button>}>{table(['日時','実行者','操作','対象・理由'],audit.filter(a=>sensitive||!a.restricted).map(a=>[a.at,a.who,a.what,<>{a.subject}<small>{a.reason}</small></>]))}</Panel>;
 if(route==='access')return <AccessPanel system={system} access={access} setAccess={setAccess} request={accessRequest} setRequest={setAccessRequest} expired={accessExpired} setExpired={setAccessExpired} begin={begin} notify={notify}/>;
 if(route==='users')return <UsersPanel users={users} setUsers={setUsers} begin={begin}/>;
 if(route==='organization')return <OrganizationPanel organization={organization} setOrganization={setOrganization} begin={begin} system={system}/>;
 if(route==='settings')return <SettingsPanel executive={executive} system={system} started={productionStarted} setStarted={setProductionStarted} settings={settings} setSettings={setSettings} begin={begin} go={go}/>;
 return null;
 }
 const screenTitle=screenCatalog.find(x=>x[0]===route)?.[1]||'経営ダッシュボード';
 return <><div className="preview-bar" inert={menu?true:undefined}><span>画面案 <b>Phase 1</b><span className="preview-detail"> · 架空データ／再読込でリセット</span></span><div><label>役割 <select aria-label="プレビューの役割" value={role} onChange={e=>roleChange(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>状態 <select aria-label="プレビューの状態" value={scenario} onChange={e=>{const value=e.target.value;if(value==='遅着データ'){setExpenses(xs=>[...xs,{id:'LATE-'+Date.now(),date:'2026-09-09',merchant:'サンプル遅着決済',amount:1200,owner:'担当A',business:'',state:'対象未分類',source:'UPSIDER'}]);setClosing(x=>x==='締め済み'?'再締め待ち':x);setRoute('closing');setScenario('通常')}else if(value==='運用開始前'){setProductionStarted(false);setSettings(x=>({...x,startedAt:'',startedBy:''}));setRoute('settings');setScenario('通常')}else{setScenario(value);if(value==='照合失敗')setCloseReady(false)}}}>{['通常','空','読込中','通信エラー','競合','ログイン','未登録','無効化','セッション期限切れ','権限不足','運用開始前','照合失敗','連携確認待ち','遅着データ'].map(s=><option key={s}>{s}</option>)}</select></label></div></div>
 {printPreview&&<div className="print-toolbar"><strong>印刷プレビュー</strong><span>現在の表示条件・閲覧できる項目だけを印刷します。</span><button onClick={()=>setPrintPreview(false)}>画面に戻る</button><button onClick={()=>window.print()}>印刷・PDF保存</button></div>}
 <div className={printPreview?'app-shell print-preview':'app-shell'}><aside ref={drawer} role={menu?'dialog':undefined} aria-modal={menu?true:undefined} aria-label={menu?'メインメニュー':undefined} className={menu?'open':''}><div className="brand"><div><strong>ATT 経営管理</strong><small>Management Board</small></div><button className="mobile-only icon-btn" aria-label="メニューを閉じる" onClick={()=>setMenu(false)}><X size={22}/></button></div><nav aria-label="メインメニュー">{nav.map(([id,label],i)=>{const Icon=icons[id];return <React.Fragment key={id}>{['accounts','users'].includes(id)&&<div className="nav-divider"/>}<button aria-current={route===id?'page':undefined} className={route===id?'selected':''} onClick={()=>go(id)}><Icon size={20}/>{label}</button></React.Fragment>})}</nav><div className="profile"><ShieldCheck size={18}/><span>{role}<small>画面表示の確認中</small></span></div></aside>{menu&&<button className="scrim" aria-label="メニューを閉じる" onClick={()=>setMenu(false)}/>}
 <main id="main" inert={menu?true:undefined}><header className="page-header"><div className="title-row"><button className="mobile-only icon-btn" aria-label="メニューを開く" aria-expanded={menu} onClick={()=>setMenu(true)}><List size={25}/></button><div><p className="eyebrow">ATT / {role}</p><h1>{screenTitle}</h1></div></div><div className="header-actions">{headerActions}</div></header>
 {['ログイン','未登録','無効化','セッション期限切れ','権限不足'].includes(scenario)?<div className="empty panel"><Lock size={35}/><h2>{scenario==='ログイン'?'ATT 経営管理ボード':scenario==='未登録'?'このメールアドレスは登録されていません':scenario==='無効化'?'このアカウントは無効です':scenario==='セッション期限切れ'?'もう一度ログインしてください':'この情報を表示する権限がありません'}</h2><p>{scenario==='ログイン'?'登録済みのGoogleアカウントでログインしてください。':'利用者の登録・権限はシステム担当へ確認してください。'}</p><p>info@mfp-design.jp</p><button className="primary" onClick={()=>setScenario('通常')}>{scenario==='ログイン'?'Googleでログイン（画面案）':'画面案の通常表示へ戻る'}</button></div>:scenario==='空'?<div className="empty panel"><SquaresFour size={34}/><h2>まだデータがありません</h2><p>入力を始めると、この画面で確認できます。</p><button onClick={()=>setScenario('通常')}>サンプルのある状態を見る</button></div>:scenario==='読込中'?<div className="empty panel" role="status"><p>読み込んでいます…</p><button onClick={()=>setScenario('通常')}>読込完了の状態へ</button></div>:<>
 {scenario==='通信エラー'&&<div className="notice danger" role="alert"><WarningCircle size={22}/><div>最新情報を取得できません。表示中の内容は前回取得時のものです。<button onClick={()=>setScenario('通常')}>再読み込み</button></div></div>}
 {scenario==='競合'&&<div className="notice" role="status">他の利用者が同じ記録を更新した場面です。フォームの保存時に確認できます。</div>}
 {route==='dashboard'?dashboard():route==='deals'?<DealsPanel deals={deals} setDeals={setDeals} revenue={revenue} setRevenue={setRevenue} accounts={accounts} businesses={businesses} members={members} stages={stages} begin={begin} focusDeal={focusDeal} setFocusDeal={setFocusDeal} go={go} saveGuard={saveGuard}/>:route==='revenue'?<RevenuePanel revenue={revenue} setRevenue={setRevenue} begin={begin} saveGuard={saveGuard} today={TODAY} role={role}/>:route==='expenses'?<ExpensePanel expenses={expenses} setExpenses={setExpenses} members={members} businesses={businesses} begin={begin} saveGuard={saveGuard} tab={expenseTab} setTab={setExpenseTab} role={role} held={scenario==='連携確認待ち'}/>:route==='closing'?closingView():secondary()}
 </>}
 <footer className="page-footer"><span>AT THE TOP · Management Board</span><span>表示金額は税込・日本円</span></footer></main></div>
 {toast&&<div role="status" className="toast"><CheckCircle size={21}/>{toast}</div>}{dialog&&<Dialog key={dialog.title} spec={dialog} onClose={()=>setDialog(null)} scenario={scenario} changed={notify}/>}</>
}
