import React,{useState,useEffect,useRef} from 'react';
import {SquaresFour,Handshake,Receipt,Wallet,CalendarCheck,NotePencil,ChatsCircle,Flag,Lightbulb,Buildings,Users,ChartBar,Coins,ClockCounterClockwise,Gear,ShieldCheck,List,X,Plus,ArrowRight,ArrowLeft,DownloadSimple,Printer,CheckCircle,WarningCircle,FunnelSimple,MagnifyingGlass,CaretRight,ArrowCounterClockwise,Lock,SignIn} from '@phosphor-icons/react';
import Chart from 'chart.js/auto';
import '@fontsource/noto-sans-jp/400.css';
import '@fontsource/noto-sans-jp/500.css';
import '@fontsource/noto-sans-jp/700.css';
import '@fontsource/zen-kaku-gothic-new/700.css';
import {businesses,members,stages,seedDeals,seedRevenue,seedExpenses,rangeFor,screenCatalog} from './data.js';
const icons={dashboard:SquaresFour,deals:Handshake,revenue:Receipt,expenses:Wallet,closing:CalendarCheck,activities:NotePencil,support:ChatsCircle,projects:Flag,ideas:Lightbulb,accounts:Buildings,organization:Users,budgets:ChartBar,payroll:Coins,audit:ClockCounterClockwise,users:Users,access:ShieldCheck,settings:Gear,login:SignIn};
const money=n=>'¥'+Number(n).toLocaleString('ja-JP');
const fmt=s=>s?.replaceAll('-','/');
const roles=['経営者','総務担当','システム担当'];
const TODAY='2026-09-11';
const field=(name,label,type='text',options,extra={})=>({name,label,type,options,required:true,...extra});
const options=(items,empty)=>[...(empty?[empty]:[]),...items];
function Tag({children,tone='neutral'}){return <span className={'tag '+tone}>{children}</span>}
function Panel({title,subtitle,action,children,className=''}){return <section className={'panel '+className}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
function ChartView({confirmed,pending,labels}){
 const canvas=useRef(null);
 useEffect(()=>{const chart=new Chart(canvas.current,{type:'bar',data:{labels,datasets:[{label:'確定分',data:confirmed,backgroundColor:'#5977B0',borderRadius:4,maxBarThickness:54},{label:'未確定分',data:pending,backgroundColor:'#BCC9E4',borderRadius:4,maxBarThickness:54}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{x:{stacked:true,grid:{display:false},ticks:{color:'#AEB4D4'}},y:{stacked:true,beginAtZero:true,grid:{color:'#2B3153'},border:{display:false},ticks:{color:'#AEB4D4',callback:n=>n/10000+'万'}}}}});return()=>chart.destroy()},[confirmed.join(','),pending.join(','),labels.join(',')]);
 return <div className="chart"><canvas ref={canvas} role="img" aria-label={`着地見込み。${labels.map((x,i)=>`${x}: 確定分${money(confirmed[i])}、未確定分${money(pending[i])}`).join('。')}`}/></div>
}
function Dialog({spec,onClose,scenario,changed}){
 const ref=useRef(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[conflictResolved,setConflictResolved]=useState(false),[draft,setDraft]=useState({});
 useEffect(()=>{ref.current.showModal()},[]);
 const submit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(spec.confirm&&!confirmed){setConfirmed(true);return}if(scenario==='競合'&&!conflictResolved){setDraft(f);setError('ほかの利用者が更新しました。現在値を再読み込みし、変更内容を確認してください。');return}if(scenario==='通信エラー'){setError('保存できませんでした。入力内容は保持しています。時間をおいて再試行してください。');return}const result=spec.save?.(f);if(typeof result==='string'){setError(result);setConfirmed(false);return}changed(spec.success||'保存しました。');onClose()};
 return <dialog ref={ref} onCancel={onClose} aria-labelledby="dialog-title"><form onSubmit={submit} onChange={()=>setConfirmed(false)}><header><div><p className="eyebrow">{spec.eyebrow||'内容の確認'}</p><h2 id="dialog-title">{spec.title}</h2></div><button type="button" className="icon-btn" onClick={onClose} aria-label="閉じる"><X size={21}/></button></header>
 <div className="dialog-body">{spec.text&&<p className="dialog-intro">{spec.text}</p>}{spec.content}
 <div className="form-grid">{spec.fields?.map(f=><label key={f.name} className={f.type==='textarea'?'wide':''}>{f.label}{f.required&&<span className="required">必須</span>}{f.type==='select'?<select name={f.name} defaultValue={f.value||''} required={f.required}><option value="">選択してください</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value||''} required={f.required} rows={3}/>:<input name={f.name} type={f.type} defaultValue={f.value??''} required={f.required} min={f.type==='number'?0:undefined} step={f.type==='number'?1:undefined} readOnly={f.readOnly}/>}</label>)}</div>
 {spec.confirm&&confirmed&&<p className="notice"><CheckCircle size={20}/>入力内容をこのまま登録します。よろしければ「確定する」を押してください。</p>}
 {error&&<div className="notice danger" role="alert"><WarningCircle size={22}/><div>{error}{scenario==='競合'&&Object.keys(draft).length>0&&<dl className="conflict-values">{spec.fields?.map(f=><React.Fragment key={f.name}><dt>{f.label}</dt><dd>現在値：{f.value||'未設定'}<br/>自分の変更：{draft[f.name]||'未設定'}</dd></React.Fragment>)}</dl>}{scenario==='競合'&&<p><button type="button" onClick={()=>{setError('現在値を再読み込みしました。もう一度確認してください。');setConflictResolved(true);setConfirmed(false)}}>現在値を再読み込み</button></p>}</div></div>}</div>
 <footer><button type="button" onClick={onClose}>キャンセル</button><button type="submit" className={spec.danger?'danger-btn':'primary'}>{spec.confirm?(confirmed?'確定する':'内容を確認'):spec.button||'保存する'}</button></footer></form></dialog>
}
export function App(){
 const [role,setRole]=useState('経営者'),[route,setRoute]=useState('dashboard'),[menu,setMenu]=useState(false),[scenario,setScenario]=useState('通常'),[toast,setToast]=useState(''),[dialog,setDialog]=useState(null);
 const [deals,setDeals]=useState(seedDeals),[revenue,setRevenue]=useState(seedRevenue),[expenses,setExpenses]=useState(seedExpenses),[closing,setClosing]=useState('未締め'),[closeReady,setCloseReady]=useState(false),[closeHistory,setCloseHistory]=useState([]);
 const [period,setPeriod]=useState('1か月'),[month,setMonth]=useState('2026-09'),[part,setPart]=useState(0),[business,setBusiness]=useState('すべての事業'),[member,setMember]=useState('すべての担当'),[stage,setStage]=useState('すべての段階'),[search,setSearch]=useState(''),[expenseTab,setExpenseTab]=useState('すべて');
 const [access,setAccess]=useState('申請中'),[comments,setComments]=useState([{id:1,business:'FP事業',member:'担当A',text:'次回の相談では、継続支援の内容を具体化。必要なら提案前に一緒に確認したい。',at:'2026/09/10 16:30'}]);
 const [activities,setActivities]=useState([{name:'提案内容の確認',business:'FP事業',member:'担当A',date:'2026-09-08',next:'2026-09-10',status:'未着手'}]);
 const [accounts,setAccounts]=useState([{name:'サンプル商事',type:'法人'},{name:'サンプル企画',type:'法人'}]);
 const [ideas,setIdeas]=useState([{text:'新規相談の前に、事前アンケートを共通化する。',business:'FP事業',status:'検討中'}]);
 const [budgetValue,setBudgetValue]=useState(700000),[payrollValue,setPayrollValue]=useState(250000);
 const [projects,setProjects]=useState([{name:'採用サイトの見直し',due:'2026-09-30',owner:'担当C',status:'進行中',budget:300000,outcome:'募集要件のたたき台を作成',problem:'写真素材の準備'}]);
 const [audit,setAudit]=useState([{at:'2026/09/10 16:30',who:'総務（サンプル）',what:'売上を計上',subject:'管理職研修 秋季プログラム',reason:'通常入力'}]);
 const executive=role==='経営者',system=role==='システム担当',sensitive=executive||(system&&access==='許可中');
 const available=id=>!(['support','budgets','payroll'].includes(id)&&!sensitive)&&!(['users','settings','organization'].includes(id)&&!system)&&!(id==='access'&&role==='総務担当')&&!(id==='audit'&&role==='総務担当');
 const nav=screenCatalog.filter(([id])=>id!=='login'&&available(id));
 const range=rangeFor(period,month,part);const inRange=d=>d>=range.start&&d<=range.end;
 const match=row=>(business==='すべての事業'||row.business===business)&&(member==='すべての担当'||row.member===member)&&(stage==='すべての段階'||(deals.find(d=>d.id===row.deal)?.stage||row.stage||'成約')===stage);
 const scoped=revenue.filter(r=>match(r)&&inRange(r.date)),actual=scoped.filter(r=>r.booked).reduce((n,r)=>n+r.amount,0),confirmed=scoped.reduce((n,r)=>n+r.amount,0),potential=deals.filter(d=>match(d)&&inRange(d.revenueDate)&&!['成約','失注'].includes(d.stage)).reduce((n,d)=>n+d.amount,0);
 const chartBusinesses=business==='すべての事業'?[...new Set([...scoped.map(r=>r.business),...deals.filter(d=>match(d)&&inRange(d.revenueDate)&&!['成約','失注'].includes(d.stage)).map(d=>d.business)])]:[business];
 const monthExpenses=expenses.filter(e=>inRange(e.date)),scopedExpenses=monthExpenses.filter(e=>business==='すべての事業'||e.business===business),cost=scopedExpenses.reduce((n,e)=>n+e.amount,0),restrictedFilter=member!=='すべての担当'||stage!=='すべての段階';
 const go=id=>{setRoute(id);setMenu(false);setSearch('');setScenario('通常')};
 const notify=text=>{setToast(text);setAudit(a=>[{at:'2026/09/11 09:00',who:role+'（サンプル）',what:text,subject:screenCatalog.find(x=>x[0]===route)?.[1],reason:'画面案での操作'},...a])};
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(!available(route))setRoute(system?'settings':'dashboard')},[role,access]);
 const roleChange=r=>{setRole(r);setDialog(null);setScenario('通常');setRoute(r==='システム担当'?'settings':'dashboard')};
 const begin=spec=>setDialog(spec);
 const saveGuard=()=>closing==='締め済み'?'この月は締め済みです。経営者に締め解除を依頼してください。':undefined;
 const classify=e=>begin({title:e.business?'経費の分類を修正':'経費の対象事業を登録',text:`${e.date} · ${e.merchant} · ${money(e.amount)} / ${e.owner}`,confirm:true,fields:[field('business','対象事業','select',[...businesses,'全社共通'],{value:e.business}),...(e.business?[field('reason','修正理由','textarea')]:[])],save:f=>{const err=saveGuard();if(err)return err;setExpenses(xs=>xs.map(x=>x.id===e.id?{...x,business:f.business,state:'分類済み',reason:f.reason||'',respondent:role}:x))},success:'経費の分類を登録しました。'});
 const table=(headers,rows)=><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j} data-label={headers[j]}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty"><MagnifyingGlass size={28}/><h3>該当するデータがありません</h3><p>検索語や絞り込み条件を変更してください。</p></div>}</div>;
 const searchbar=(label='名称で検索')=><label className="search"><MagnifyingGlass size={19}/><span className="sr-only">{label}</span><input value={search} placeholder={label} onChange={e=>setSearch(e.target.value)}/></label>;
 const filters=<div className="filters"><label><FunnelSimple size={17}/><span className="sr-only">事業</span><select aria-label="事業で絞り込み" value={business} onChange={e=>setBusiness(e.target.value)}>{options(businesses,'すべての事業').map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">担当者</span><select aria-label="担当者で絞り込み" value={member} onChange={e=>setMember(e.target.value)}>{options(members,'すべての担当').map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">案件段階</span><select aria-label="案件段階で絞り込み" value={stage} onChange={e=>setStage(e.target.value)}>{options(stages,'すべての段階').map(x=><option key={x}>{x}</option>)}</select></label><button className="text-btn" onClick={()=>{setBusiness('すべての事業');setMember('すべての担当');setStage('すべての段階')}}>条件をクリア</button></div>;
 const exportCsv=()=>{const rows=[['分析期間',range.start,range.end],['事業',business],['担当',member],['段階',stage],['売上計上額',actual],['売上着地見込み',confirmed+potential]];if(!restrictedFilter)rows.push(['経費総額',cost]);if(sensitive&&!restrictedFilter&&period!=='10日毎')rows.push(['利益',actual-cost-(business==='すべての事業'?payrollValue:0)]);const q=v=>'"'+String(v).replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ATT_画面案_架空集計.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('選択条件のCSVを出力しました。')};
 const headerActions=route==='dashboard'?<><button onClick={exportCsv}><DownloadSimple size={17}/>CSV</button><button onClick={()=>window.print()}><Printer size={17}/>印刷</button></>:null;
 function dashboard(){return <>
 <div className="period-bar"><div className="segments" aria-label="分析期間">{['10日毎','1か月','3か月','6か月','1年'].map(p=><button key={p} aria-pressed={period===p} className={p===period?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div><label className="month"><span className="sr-only">対象月</span><input type="month" value={month} min="2025-10" max="2026-09" onChange={e=>e.target.value&&setMonth(e.target.value)}/></label>{period==='10日毎'&&<select aria-label="管理区分" value={part} onChange={e=>setPart(Number(e.target.value))}>{['上旬（1〜10日）','中旬（11〜20日）','下旬（21日〜月末）'].map((p,i)=><option key={p} value={i}>{p}</option>)}</select>}</div>
 <p className="range">{fmt(range.start)} — {fmt(range.end)} <span>比較：{fmt(range.prevStart)} — {fmt(range.prevEnd)}</span></p>{filters}
 {restrictedFilter&&<p className="notice">担当者・案件段階での絞り込み中です。経費・予算・利益は集計対象から外れます。</p>}
 <div className="metrics"><Metric label="売上計上額" value={money(actual)} sub="計上実績日の合計"/><Metric label="売上着地見込み" value={money(confirmed+potential)} sub={`確定分 ${money(confirmed)} / 未確定分 ${money(potential)}`}/>{!restrictedFilter&&<><Metric label="経費総額" value={money(cost)} sub={`利用日の実績 · 人件費を除く${business==='すべての事業'?' · 未分類を含む':''}`}/>{sensitive&&<Metric label={business==='すべての事業'?'全社利益':'事業利益'} value={period==='10日毎'&&business==='すべての事業'?'—':money(actual-cost-(business==='すべての事業'?payrollValue:0))} sub={period==='10日毎'&&business==='すべての事業'?'10日毎では全社利益を計算しません':business==='すべての事業'?'経費・全社人件費を控除':'全社共通費・人件費の配賦前'}/>}</>}</div>
 <div className="dashboard-grid"><Panel title="売上の着地見込み" subtitle="選択期間の事業別内訳" action={<Tag>税込</Tag>}><ChartView confirmed={chartBusinesses.map(b=>scoped.filter(r=>r.business===b).reduce((n,r)=>n+r.amount,0))} pending={chartBusinesses.map(b=>deals.filter(d=>d.business===b&&match(d)&&inRange(d.revenueDate)&&!['成約','失注'].includes(d.stage)).reduce((n,d)=>n+d.amount,0))} labels={chartBusinesses}/><div className="legend"><span><i className="solid"/>確定分 {money(confirmed)}</span><span><i className="pale"/>未確定分 {money(potential)}</span></div><p className="small">確定分＝計上済み＋成約済みの未計上予定。未確定分は全件成約した場合の金額です。</p></Panel>
 <Panel title="確認すること" subtitle="未完了の入力と次の行動"><button className="action-row" onClick={()=>{setExpenseTab('対象未分類');go('expenses')}}><Wallet size={22}/><span><strong>経費の対象事業</strong><small>未分類 {expenses.filter(e=>!e.business).length}件</small></span><CaretRight/></button><button className="action-row" onClick={()=>go('revenue')}><Receipt size={22}/><span><strong>請求・入金の確認</strong><small>入金待ち {money(revenue.reduce((n,r)=>n+r.invoiced-r.paid,0))}</small></span><CaretRight/></button><button className="action-row" onClick={()=>go('activities')}><CalendarCheck size={22}/><span><strong>次の行動を確認</strong><small>期限超過 {activities.filter(a=>a.status==='未着手'&&a.next&&a.next<TODAY).length}件</small></span><CaretRight/></button><div className="closing-mini"><span>9月の月次締め</span><Tag>{closing}</Tag><p>目標：2026/10/10</p><button className="text-btn" onClick={()=>go('closing')}>締め状況を見る <ArrowRight size={16}/></button></div></Panel></div>
 {sensitive&&!restrictedFilter&&<Panel title={period==='10日毎'?'9月の参考情報':'9月の予算と経費の内訳'} subtitle={period==='10日毎'?'月次予算・人件費は日割りせず、実績と分けて表示':'架空の月次予算・人件費'}><div className="summary-strip"><div>売上予算<strong>{money(800000+budgetValue)}</strong></div><div>経費予算<strong>{money(300000)}</strong></div><div>全社人件費<strong>{money(payrollValue)}</strong></div><div>全社共通費<strong>{money(monthExpenses.filter(e=>e.business==='全社共通').reduce((n,e)=>n+e.amount,0))}</strong></div></div></Panel>}
 <Panel title="案件の状況" subtitle="2026年9月の案件サンプル" action={<button className="text-btn" onClick={()=>go('deals')}>案件一覧 <ArrowRight size={16}/></button>}>{table(['案件','事業・担当','段階','金額'],deals.filter(match).map(d=>[<button className="text-btn" onClick={()=>dealDetail(d)}>{d.name}</button>,<>{d.business}<small>{d.member}</small></>,<Tag>{d.stage}</Tag>,money(d.amount)]))}</Panel>
 {sensitive&&<Panel title="支援記録" subtitle="経営者だけに共有するコメント" action={<button onClick={addComment}><Plus size={17}/>コメント</button>}>{comments.slice(0,2).map(c=><article className="comment" key={c.id}><p>{c.text}</p><small>{c.business} · {c.member} · 経営者（サンプル） · {c.at}</small></article>)}</Panel>}
 </>}
 function Metric({label,value,sub}){return <section className="metric"><p>{label}</p><strong>{value}</strong><small>{sub}</small></section>}
 function addComment(){begin({title:'支援コメントを記録',text:'投稿後は上書きせず、訂正コメントを追記します。',fields:[field('business','対象事業','select',businesses,{required:false}),field('member','対象メンバー','select',members,{required:false}),field('deal','関連案件','select',deals.map(d=>d.name),{required:false}),field('activity','関連活動','select',activities.map(a=>a.name),{required:false}),field('text','コメント','textarea')],save:f=>{if(!f.business&&!f.member)return '対象事業または対象メンバーを一つ以上選んでください。';setComments(cs=>[{...f,id:Date.now(),at:'2026/09/11 09:00'},...cs])},success:'支援コメントを記録しました。'})}
 function dealDetail(d){begin({title:d.name,text:`${d.business} · ${d.member} · ${money(d.amount)}`,content:<dl className="details"><dt>取引先</dt><dd>{d.account}</dd><dt>案件段階</dt><dd>{d.stage}</dd><dt>成約予定日</dt><dd>{fmt(d.due)}</dd><dt>売上計上予定日</dt><dd>{fmt(d.revenueDate)}</dd></dl>,button:d.stage==='成約'?'売上を確認':'成約内容を確認',save:()=>{if(d.stage==='成約'){go('revenue');return}setTimeout(()=>begin({title:'成約を登録',text:`${d.name} / ${money(d.amount)}。同額の売上予定を作成します。売上実績はまだ計上されません。`,confirm:true,save:()=>{setDeals(ds=>ds.map(x=>x.id===d.id?{...x,stage:'成約'}:x));setRevenue(rs=>[...rs,{id:'R-'+Date.now(),deal:d.id,name:d.name,business:d.business,member:d.member,amount:d.amount,date:d.revenueDate,booked:false,invoiced:0,paid:0,mode:'一括'}]);go('revenue')},success:'成約を登録し、売上予定を作成しました。'}),0)}})}
 function addDeal(){begin({title:'案件を登録',fields:[field('name','案件名'),field('business','事業','select',businesses),field('account','取引先','select',accounts.map(a=>a.name)),field('member','主担当者','select',members),field('stage','案件段階','select',stages.filter(s=>!['成約','失注'].includes(s)),{value:'見込み'}),field('amount','全件成約時の税込金額（円）','number'),field('due','成約予定日','date'),field('revenueDate','売上計上予定日','date')],save:f=>setDeals(ds=>[{...f,id:'D-'+Date.now(),amount:Number(f.amount)},...ds]),success:'案件を登録しました。'})}
 function revenueDetail(r){begin({title:r.name,text:`${money(r.amount)} / ${r.booked?'計上済み':'売上予定'} / ${r.mode}`,fields:[field('date',r.booked?'請求・入金の実績日':'売上計上実績日','date',null,{value:TODAY}),...(r.booked?[field('operation','登録する実績','select',['請求','入金']),field('amount','税込実績額（円）','number',null,{value:r.amount})]:[])],confirm:true,button:'登録する',save:f=>{const err=saveGuard();if(err)return err;const value=Number(f.amount);if(r.booked){if(value<=0)return '実績額は1円以上で入力してください。';if(f.operation==='請求'&&r.invoiced+value>r.amount)return '売上計上額を超える請求は登録できません。差額は理由付きの調整として扱います。';if(f.operation==='入金'&&r.paid+value>r.invoiced)return '請求済額を超える入金は登録できません。';}setRevenue(xs=>xs.map(x=>x.id!==r.id?x:!r.booked?{...x,booked:true,date:f.date}:f.operation==='請求'?{...x,invoiced:x.invoiced+value,invoiceDate:f.date}:{...x,paid:x.paid+value,paidDate:f.date}));},success:r.booked?'実績を登録しました。':'売上を計上しました。'})}
 function expensesView(){const list=expenses.filter(e=>(expenseTab==='すべて'||e.state===expenseTab)&&`${e.merchant} ${e.business} ${e.owner}`.includes(search));return <><div className="toolbar"><div className="segments">{['すべて','対象未分類','分類済み','連携確認待ち'].map(t=><button key={t} className={expenseTab===t?'active':''} onClick={()=>setExpenseTab(t)}>{t}</button>)}</div><button className="primary" onClick={()=>begin({title:'手入力経費を登録',text:'UPSIDER以外の支出を登録します。',fields:[field('date','利用日','date',null,{value:TODAY}),field('merchant','支払先・内容'),field('owner','支払者','select',[...members,'会社']),field('amount','税込金額（円）','number'),field('business','対象事業','select',[...businesses,'全社共通'])],save:f=>{const err=saveGuard();if(err)return err;setExpenses(xs=>[...xs,{...f,id:'E-'+Date.now(),amount:Number(f.amount),source:'手入力',state:'分類済み'}])}})}><Plus size={17}/>手入力経費</button></div>{searchbar('利用先・事業・利用者で検索')}
 <Panel title="経費明細" subtitle="利用日で集計。対象未分類も全社経費に含まれます。">{table(['利用日・利用先','利用者','税込金額','対象事業','状態','操作'],list.map(e=>[<>{fmt(e.date)}<strong>{e.merchant}</strong><small>{e.source}</small></>,e.owner,money(e.amount),<span>{e.business||'未回答'}{e.reason&&<small>理由：{e.reason}</small>}{e.respondent&&<small>回答者：{e.respondent}</small>}</span>,<Tag tone={e.business?'good':'warn'}>{e.state}</Tag>,<button onClick={()=>classify(e)}>{e.business?'回答を修正':'事業を選択'}</button>]))}</Panel>
 <p className="small">未回答の経費は毎月1・11・21日10:00に、元のSlackスレッドで1件ずつ再通知します。</p></>}
 function closingView(){const pending=expenses.filter(e=>!e.business).length;const locked=closing==='締め済み';return <><div className="period-bar"><h2>2026年9月</h2><Tag tone={locked?'good':'warn'}>{closing}</Tag><span className="small">締め目標日：2026/10/10</span></div><Panel title="締める前に確認" subtitle="直前の連携確認が完了してから締めを確定します。"><div className="check-row"><span>経費の対象事業</span>{pending?<button className="text-btn" onClick={()=>{setExpenseTab('対象未分類');go('expenses')}}>未回答 {pending}件を確認 <ArrowRight size={17}/></button>:<Tag tone="good">確認済み</Tag>}</div><div className="check-row"><span>連携確認待ち</span><Tag tone="good">0件</Tag></div><div className="check-row"><span>Slackとの直前照合</span><Tag tone={closeReady?'good':'warn'}>{closeReady?'照合済み（画面案）':'未実施'}</Tag></div><div className="check-row"><span>売上・請求・入金</span><button className="text-btn" onClick={()=>go('revenue')}>明細を見る <ArrowRight size={17}/></button></div><div className="panel-footer">{!locked&&<button onClick={()=>{setCloseReady(true);notify('画面案の照合を完了しました。')}}>照合を実行</button>}{executive?locked?<button onClick={()=>begin({title:'9月の締めを解除',text:'解除後は明細を編集できます。訂正後は再度締めてください。',fields:[field('reason','解除理由','textarea')],confirm:true,save:()=>{setClosing('再締め待ち');setCloseReady(false)},success:'締めを解除しました。'})}>理由を付けて解除</button>:<button disabled={pending>0||!closeReady} className="primary" onClick={()=>begin({title:'2026年9月を締める',text:'売上・経費・予算などの通常編集を停止します。訂正には理由付きの締め解除が必要です。',confirm:true,save:()=>{setClosing('締め済み');setCloseHistory(h=>[...h,{version:h.length+1,date:'2026/09/11',by:'経営者（サンプル）'}])},success:'2026年9月を締めました。'})}>月次を締める</button>:<p className="small">総務担当は下書き・確認まで行えます。確定は経営者が行います。</p>}</div></Panel><Panel title="締めの履歴" subtitle="過去の締め版は保持します。"><p className="muted">{closeHistory.length?closeHistory.map(h=><span key={h.version}>第{h.version}版 · {h.date} · {h.by}<br/></span>):'この月の締めはまだ確定していません。'}</p></Panel></>}
 function secondary(){
 if(route==='support')return <Panel title="支援コメント" subtitle="経営者限定。訂正は新しいコメントで追記します。" action={<button className="primary" onClick={addComment}><Plus size={17}/>コメントを記録</button>}>{comments.map(c=><article className="comment" key={c.id}><Tag>{c.business||c.member}</Tag><p>{c.text}</p><small>{c.member} · 経営者（サンプル） · {c.at}</small><button className="text-btn" onClick={addComment}>訂正を追記</button></article>)}</Panel>;
 if(route==='activities')return <Panel title="活動と次の行動" subtitle="期限・指定日・期間・日程未定を区別して確認" action={role==='総務担当'?<button className="primary" onClick={()=>begin({title:'活動を記録',fields:[field('date','活動日','date',null,{value:TODAY}),field('business','対象事業','select',businesses),field('member','対象メンバー','select',members),field('name','活動内容','textarea'),field('next','次の行動の期限','date',null,{required:false})],save:f=>setActivities(xs=>[...xs,{...f,status:'未着手'}])})}><Plus size={17}/>活動を記録</button>:null}>{table(['活動','事業・担当','次の行動','状態'],activities.map(a=>[<>{a.name}<small>{fmt(a.date)}</small></>,a.business+' / '+a.member,a.next?fmt(a.next):'日程未定',<Tag tone={a.status==='未着手'&&a.next<TODAY?'warn':'neutral'}>{a.status==='未着手'&&a.next&&a.next<TODAY?'期限超過':a.status}</Tag>]))}</Panel>;
 if(route==='projects')return <Panel title="全社プロジェクト" subtitle="期限・成果・課題から支援を判断">{projects.map((p,i)=><article className="project" key={i}><div><h3>{p.name}</h3><Tag>{p.status}</Tag></div><p>{p.outcome}</p><p className="muted">課題：{p.problem}</p><div className="summary-strip"><span>期限 {fmt(p.due)}</span><span>責任者 {p.owner}</span>{sensitive&&<span>予算 {money(p.budget)}</span>}</div><button onClick={()=>begin({title:'進捗を更新',fields:[field('status','状態','select',executive?['未着手','進行中','要支援','完了','中止']:['未着手','進行中','要支援'],{value:p.status}),field('outcome','成果','textarea',null,{value:p.outcome}),field('problem','課題','textarea',null,{value:p.problem,required:false})],save:f=>setProjects(xs=>xs.map((x,j)=>i===j?{...x,...f}:x))})}>進捗を更新</button></article>)}</Panel>;
 if(route==='ideas')return <Panel title="アイデア受信箱" subtitle="思いつきを、一つのメモで残す" action={<button className="primary" onClick={()=>begin({title:'アイデアを投稿',fields:[field('text','アイデアメモ','textarea'),field('business','関連事業','select',businesses,{required:false})],save:f=>setIdeas(xs=>[{...f,status:'未整理'},...xs])})}><Plus size={17}/>アイデアを投稿</button>}>{ideas.map((v,i)=><article className="comment" key={i}><p>{v.text}</p><div className="toolbar"><small>{v.business} · Web入力 · サンプル利用者</small><select aria-label={`アイデア${i+1}の状態`} value={v.status} onChange={e=>setIdeas(xs=>xs.map((x,j)=>i===j?{...x,status:e.target.value}:x))}>{(executive?['未整理','検討中','採用','保留','却下']:['未整理','検討中']).map(s=><option key={s}>{s}</option>)}</select></div></article>)}</Panel>;
 if(route==='accounts')return <Panel title="取引先一覧" subtitle="名称と個人・法人の区別を管理" action={<button className="primary" onClick={()=>begin({title:'取引先を登録',fields:[field('name','名称'),field('type','種別','select',['個人','法人'])],save:f=>{if(accounts.some(a=>a.name===f.name))return '同名の取引先があります。別の取引先として登録する場合は一覧で内容を確認してください。';setAccounts(xs=>[...xs,f])}})}><Plus size={17}/>取引先を登録</button>}>{table(['名称','種別','操作'],accounts.map(a=>[a.name,a.type,<button onClick={()=>begin({title:'取引先を統合',text:`統合元：${a.name}。案件・売上との関係と元の識別子は保持します。`,fields:[field('target','統合先','select',accounts.filter(x=>x!==a).map(x=>x.name)),field('reason','統合理由','textarea')],confirm:true,save:f=>setAccounts(xs=>xs.filter(x=>x!==a))})}>統合を確認</button>]))}</Panel>;
 if(route==='budgets'||route==='payroll')return <Panel title={route==='budgets'?'2026年9月 月次予算':'2026年9月 全社人件費'} subtitle="経営者限定・税込・円単位。締め後の変更は締め解除が必要です。" action={<button onClick={()=>begin({title:'月次金額を変更',text:route==='budgets'?'FP事業の売上予算を変更します。':'全社人件費を変更します。',fields:[field('amount','税込金額（円）','number',null,{value:route==='budgets'?budgetValue:payrollValue}),field('reason','変更理由','textarea')],save:f=>{const error=saveGuard();if(error)return error;route==='budgets'?setBudgetValue(Number(f.amount)):setPayrollValue(Number(f.amount))},success:'月次金額を変更しました。'})}>金額を変更</button>}>{route==='budgets'?table(['予算種別','対象','金額'],[['売上予算','FP事業',money(budgetValue)],['事業経費予算','FP事業',money(100000)],['全社共通費予算','全社',money(200000)],['全社人件費予算','全社',money(250000)]]):<><Metric label="全社人件費" value={money(payrollValue)} sub="個人別の給与明細は保持しません。"/></>}</Panel>;
 if(route==='audit')return <Panel title="変更・操作の履歴" subtitle="閲覧できる情報の範囲で履歴を確認">{table(['日時','実行者','操作','対象・理由'],audit.map(a=>[a.at,a.who,a.what,<>{a.subject}<small>{a.reason}</small></>]))}</Panel>;
 if(route==='access')return <Panel title={system?'一時アクセスを申請':'一時アクセスの承認'} subtitle="役員限定情報へのアクセスは24時間。期限前でも取り消せます。"><div className="access-card"><ShieldCheck size={32}/><div><h3>システム担当（サンプル）</h3><p>理由：経費表示の問い合わせ調査</p><Tag tone={access==='許可中'?'good':'warn'}>{access}</Tag>{access==='許可中'&&<p>有効期限：2026/09/12 09:00（画面案）</p>}</div></div><div className="panel-footer">{system?<button className="primary" onClick={()=>begin({title:'一時アクセスを申請',fields:[field('reason','閲覧が必要な理由','textarea')],save:()=>setAccess('申請中'),success:'申請しました。経営者の承認をお待ちください。'})}>理由を付けて申請</button>:access==='許可中'?<button onClick={()=>{setAccess('取り消し済み');notify('一時アクセスを取り消しました。')}}>許可を取り消す</button>:<><button onClick={()=>{setAccess('拒否');notify('申請を拒否しました。')}}>拒否</button><button className="primary" onClick={()=>{setAccess('許可中');notify('24時間のアクセスを許可しました。')}}>24時間許可</button></>}</div></Panel>;
 if(route==='users')return <Panel title="利用者・権限" subtitle="Googleメールを許可リストに登録して管理" action={<button className="primary" onClick={()=>begin({title:'利用者を登録',fields:[field('email','Googleメールアドレス','email'),field('role','役割','select',roles)],confirm:true,success:'利用者登録の確認を完了しました（画面案・メール送信なし）。'})}><Plus size={17}/>利用者を登録</button>}>{table(['利用者','役割','状態','操作'],[['サンプル役員','経営者',<Tag tone="good">有効</Tag>,<button onClick={()=>begin({title:'利用者を無効化',text:'サンプル役員の利用を停止します。既存セッションにも反映します。',fields:[field('reason','理由','textarea')],confirm:true,danger:true,success:'無効化の確認を完了しました（画面案）。'})}>無効化</button>],['サンプル総務','総務担当',<Tag tone="good">有効</Tag>,'—']])}</Panel>;
 if(route==='organization')return <><Panel title="事業" subtitle="無効化しても過去の名称・所属を保持">{table(['事業名','有効期間','状態'],businesses.map(b=>[b,'2025/10/01 —',<Tag tone="good">有効</Tag>]))}</Panel><Panel title="メンバーの所属" subtitle="主所属は一つ、兼務先は複数登録可能">{table(['メンバー','主所属','兼務'],members.map((m,i)=>[m,businesses[i],i===0?'企業研修':'—']))}</Panel></>;
 if(route==='settings')return <><Panel title="運用の状況" subtitle="会社の窓口：info@mfp-design.jp"><div className="check-row"><span>UPSIDER連携</span><Tag tone="warn">未設定・停止中（画面案）</Tag></div><div className="check-row"><span>バックアップ</span><Tag>未接続（画面案）</Tag></div><div className="check-row"><span>障害の一次確認</span><span>花沢</span></div><div className="check-row"><span>料金プラン</span><span>Workers Freeで開始</span></div></Panel><Panel title="会計年度" subtitle="変更は次の未開始年度から。開始済みの期間は変更しません。"><p>開始月：10月</p><button onClick={()=>begin({title:'年度開始月の変更案',text:'役員承認後、次の未開始年度から適用します。',fields:[field('month','新しい開始月','select',Array.from({length:12},(_,i)=>`${i+1}月`)),field('reason','変更理由','textarea')],confirm:true,success:'年度変更の確認を完了しました（画面案）。'})}>変更内容を確認</button></Panel><p className="notice"><Lock size={20}/>本番開始後の役員限定情報には、一時アクセスの承認が必要です。</p><button onClick={()=>go('access')}>一時アクセスを申請</button></>;
 return null;
 }
 const screenTitle=screenCatalog.find(x=>x[0]===route)?.[1]||'経営ダッシュボード';
 return <><div className="preview-bar"><span>画面案 <b>Phase 1</b><span className="preview-detail"> · 架空データ／再読込でリセット</span></span><div><label>役割 <select aria-label="プレビューの役割" value={role} onChange={e=>roleChange(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>状態 <select aria-label="プレビューの状態" value={scenario} onChange={e=>setScenario(e.target.value)}>{['通常','空','読込中','通信エラー','競合','利用不可'].map(s=><option key={s}>{s}</option>)}</select></label></div></div>
 <div className="app-shell"><aside className={menu?'open':''}><div className="brand"><div><strong>ATT 経営管理</strong><small>Management Board</small></div><button className="mobile-only icon-btn" aria-label="メニューを閉じる" onClick={()=>setMenu(false)}><X size={22}/></button></div><nav aria-label="メインメニュー">{nav.map(([id,label],i)=>{const Icon=icons[id];return <React.Fragment key={id}>{['accounts','users'].includes(id)&&<div className="nav-divider"/>}<button aria-current={route===id?'page':undefined} className={route===id?'selected':''} onClick={()=>go(id)}><Icon size={20}/>{label}</button></React.Fragment>})}</nav><div className="profile"><ShieldCheck size={18}/><span>{role}<small>画面表示の確認中</small></span></div></aside>{menu&&<button className="scrim" aria-label="メニューを閉じる" onClick={()=>setMenu(false)}/>}
 <main id="main"><header className="page-header"><div className="title-row"><button className="mobile-only icon-btn" aria-label="メニューを開く" aria-expanded={menu} onClick={()=>setMenu(true)}><List size={25}/></button><div><p className="eyebrow">ATT / {role}</p><h1>{screenTitle}</h1></div></div><div className="header-actions">{headerActions}</div></header>
 {scenario==='利用不可'?<div className="empty panel"><Lock size={35}/><h2>このアカウントは利用できません</h2><p>登録状況をシステム担当へ確認してください。</p><p>info@mfp-design.jp</p><button onClick={()=>setScenario('通常')}>ログイン画面へ戻る</button></div>:scenario==='空'?<div className="empty panel"><SquaresFour size={34}/><h2>まだデータがありません</h2><p>入力を始めると、この画面で確認できます。</p><button onClick={()=>setScenario('通常')}>サンプルのある状態を見る</button></div>:scenario==='読込中'?<div className="empty panel" role="status"><p>読み込んでいます…</p><button onClick={()=>setScenario('通常')}>読込完了の状態へ</button></div>:<>
 {scenario==='通信エラー'&&<div className="notice danger" role="alert"><WarningCircle size={22}/><div>最新情報を取得できません。表示中の内容は前回取得時のものです。<button onClick={()=>setScenario('通常')}>再読み込み</button></div></div>}
 {scenario==='競合'&&<div className="notice" role="status">他の利用者が同じ記録を更新した場面です。フォームの保存時に確認できます。</div>}
 {route==='dashboard'?dashboard():route==='deals'?<><div className="toolbar">{searchbar('案件名・取引先で検索')}<button className="primary" onClick={addDeal}><Plus size={17}/>案件を登録</button></div>{filters}<Panel title="案件一覧" subtitle="成約と売上計上を分けて管理">{table(['案件・取引先','事業・担当','段階','金額','操作'],deals.filter(d=>match(d)&&`${d.name} ${d.account}`.includes(search)).map(d=>[<><strong>{d.name}</strong><small>{d.account}</small></>,<>{d.business}<small>{d.member}</small></>,<Tag tone={d.stage==='成約'?'good':'neutral'}>{d.stage}</Tag>,money(d.amount),<button onClick={()=>dealDetail(d)}>詳細 <CaretRight size={16}/></button>]))}</Panel></>:route==='revenue'?<><div className="metrics"><Metric label="売上計上済み" value={money(revenue.filter(r=>r.booked).reduce((n,r)=>n+r.amount,0))} sub="架空データ：9月"/><Metric label="未請求額" value={money(revenue.filter(r=>r.booked).reduce((n,r)=>n+r.amount-r.invoiced,0))} sub="計上済み − 請求済み"/><Metric label="未入金額" value={money(revenue.reduce((n,r)=>n+r.invoiced-r.paid,0))} sub="請求済み − 入金済み"/></div><Panel title="売上・請求・入金の明細" subtitle="予定は実績に含めません。実績日と金額で確認します。">{table(['案件','金額','状態','請求済み','入金済み','操作'],revenue.map(r=>[<>{r.name}<small>{r.business} · {fmt(r.date)}</small></>,money(r.amount),<Tag tone={r.booked?'good':'warn'}>{r.booked?'計上済み':'売上予定'}</Tag>,money(r.invoiced),money(r.paid),<button onClick={()=>revenueDetail(r)}>{r.booked?'実績を登録':'売上を計上'}</button>]))}</Panel></>:route==='expenses'?expensesView():route==='closing'?closingView():secondary()}
 </>}
 <footer className="page-footer"><span>AT THE TOP · Management Board</span><span>表示金額は税込・日本円</span></footer></main></div>
 {toast&&<div role="status" className="toast"><CheckCircle size={21}/>{toast}</div>}{dialog&&<Dialog key={dialog.title} spec={dialog} onClose={()=>setDialog(null)} scenario={scenario} changed={notify}/>}</>
}
